version: "3.8"

services:
  frontend:
    build:
      context: ./agriscan-ai
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # add other env variables your backend requires

